sudo: required
services:
    - docker
before_install:
    - docker build -t mgarcia11/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mgarcia11/react-test npm test

after_success:
    - docker build -t mgarcia11/multi-client ./client
    - docker build -t mgarcia11/multi-worker ./worker
    - docker build -t mgarcia11/multi-server ./server
    - docker build -t mgarcia11/multi-nginx ./nginx
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u $"DOCKER_ID" --password-stdin
    # Take those images and pushh them to docker hub
    - docker push -t mgarcia11/multi-client ./client
    - docker push -t mgarcia11/multi-worker ./worker
    - docker push -t mgarcia11/multi-server ./server
    - docker push -t mgarcia11/multi-nginx ./nginx